### ISSUE TITLE
port coderhaoxin/scssbase

### ISSUE THREAD

**Issue by coderhaoxin** [coderhaoxin/cssbase#1]

**Comment by coderhaoxin** [comment]
```css
textarea {
  resize: none;
}
```
